name: Docs
on:
  workflow_call:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/cache@v3
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - name: Setup docs environment
        shell: julia --color=yes --project=docs {0}
        run: |
          using Pkg;
          Pkg.instantiate()
      - name: Run doctests
        shell: julia --color=yes --project=docs {0}
        run: |
          using Documenter: DocMeta, doctest
          using AlgebraOfGraphics
          DocMeta.setdocmeta!(AlgebraOfGraphics, :DocTestSetup, :(using AlgebraOfGraphics); recursive=true)
          doctest(AlgebraOfGraphics)
      - name: Build and deploy docs
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
